/*
 * Copyright (c) BaziPardaz.Co Ltd. All rights reserved.
 * 
 * File Name        : CinematicSet.cs
 * File Description : The setting of Cinematic
 * Generated by     : Pooya Eimandar
 * Last modified by : Pooya Eimandar on 8/27/2013
 * Comment          : 
 */

using System;

namespace PersianSettings
{
    public class CinematicSet
    {
        /// <summary>
        /// Identifier of cinematic...Make sure ID will unique
        /// </summary>
        public string ID = string.Empty;

        /// <summary>
        /// Path of Movement along curves, if empty means we have not any movement
        /// </summary>
        public string PathOfCurves = string.Empty;

        /// <summary>
        /// Asset of Model, Can not be null or empty
        /// </summary>
        public string PathOfModel = string.Empty;

        /// <summary>
        /// Need skinning or not
        /// </summary>
        public bool isSkinned = false;

        /// <summary>
        /// Repeat times, 0, 1, 2,...(-1 means ForeEver)
        /// </summary>
        public int Repeat = 0;

        /// <summary>
        /// Depends on Time, Position or Both
        /// </summary>
        public string DependsOn = string.Empty;

        /// <summary>
        /// Active on time if cinematic depends on time
        /// </summary>
        public TimeSpan StartUpTime;

        /// <summary>
        /// Active on Position if cinematic depends on Position ( X = Don't care )
        /// </summary>
        public string StartUpPosition = "X X X";

        /// <summary>
        /// if cinematic depends on specific position of character then we must specify character's name
        /// </summary>
        public string PositionDependsOnWho = string.Empty;
    }
}
