/*
 * Copyright (c) BaziPardaz.Co Ltd. All rights reserved.
 * 
 * File Name        : DebugInfo.cs
 * File Description : Show status
 * Generated by     : Pooya Eimandar
 * Last modified by : Pooya Eimandar on 8/19/2013
 * Comment          : 
 */
namespace Debugger
{
    public class DebugInfo
    {
        #region Fields & Properties

        const string endL = "\r\n";

        string statusData;
        public string Get
        {
            get
            {
                return this.statusData;
            }
        }
        public int XLenght
        {
            get;
            private set;
        }
        public int YLenght
        {
            get;
            private set;
        }

        public uint DrawCalls;
        public uint VisibleLights;
        public uint ShadowCasterLights;
        public uint ShadowCasterMeshes;
        public uint VisibleParticleSystems;
        public uint VisibleModels;

        #endregion

        #region Constructor

        public DebugInfo()
        {
            this.statusData = string.Empty;
            Reset();
        }

        #endregion

        #region Methods

        public void Reset()
        {
            this.DrawCalls = this.VisibleLights = this.ShadowCasterMeshes = this.ShadowCasterLights =
                this.VisibleParticleSystems = 0;
            this.statusData = string.Empty;
            this.YLenght = 0;
            this.XLenght = 0;
        }

        public void Add(string value)
        {
            if (value == null)
            {
                return;
            }
            if (value.Length > this.XLenght)
            {
                this.XLenght = value.Length;
            }
            this.statusData += string.Concat(value, endL);
            this.YLenght++;
        }

        #endregion
    }
}