/*
 * Copyright (c) BaziPardaz.Co Ltd. All rights reserved.
 * 
 * File Name        : Convertes.cs
 * File Description : 
 * Generated by     : Pooya Eimandar
 * Last modified by : Pooya Eimandar on 9/1/2013
 * Comment          : 
 */

using System;
using System.Globalization;
using System.Windows.Data;

namespace PersianEditor
{
    /// <summary>
    /// XAML binding converters for float to string and vice versa
    /// </summary>
    class FloatToStringConvertter : IValueConverter
    {
        public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
        {
            var format = parameter as string;
            if (!string.IsNullOrEmpty(format))
            {
                return string.Format(culture, format, value);
            }
            else
            {
                return value.ToString();
            }
        }

        public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
        {
            return System.Convert.ToSingle(parameter);
        }
    }

    class Converters
    {
        /// <summary>
        /// Convert GDI Color to XNA Color
        /// </summary>
        /// <param name="Color"></param>
        /// <returns></returns>
        public static Microsoft.Xna.Framework.Color ToXNAColor(System.Windows.Media.Color Color)
        {
            return new Microsoft.Xna.Framework.Color(Color.R, Color.G, Color.B, Color.A);
        }

        /// <summary>
        /// Convert GUI Color to XNA Color
        /// </summary>
        /// <param name="Color"></param>
        /// <returns></returns>
        public static System.Windows.Media.Color ToGUIColor(Microsoft.Xna.Framework.Color Color)
        {
            return System.Windows.Media.Color.FromArgb(Color.A, Color.R, Color.G, Color.B);
        }
    }
}
