/*
 * Copyright (c) BaziPardaz.Co Ltd. All rights reserved.
 * 
 * File Name        : DirectionalLight.cs
 * File Description : The directional light
 * Generated by     : Pooya Eimandar 
 * Last modified by : Pooya Eimandar on 11/8/2013
 * Comment          : 
 */

using Microsoft.Xna.Framework;

namespace PersianCore.Graphics.Lights.Deferred
{
    /// <summary>
    /// The directional light
    /// </summary>
    public class DirectionalLight : Light
    {
        #region Fields & Properties

        /// <summary>
        /// Directional of light
        /// </summary>
        public Vector3 Direction;

        #endregion

        #region Constructor/Destructor

        public DirectionalLight(Vector3 rotation, Color color, float intensity)
        {
            this.lightType = LightType.Directional;
            this.Color = color.ToVector4();
            this.Intensity = intensity;
            this.rotation = rotation;
            this.World = this.rotation.ToRotationMatrix();
            this.radius = 1;
            Update();
        }

        ~DirectionalLight()
        {
        }

        #endregion

        #region Update

        public void Update()
        {
            this.Direction = Vector3.TransformNormal(Vector3.Normalize(this.World.Backward), Persian.Camera.View);
            this.Direction.Normalize();
        }

        #endregion
    }
}