/*
 * Copyright (c) BaziPardaz.Co Ltd. All rights reserved.
 * 
 * File Name        : ImporterContext.cs
 * File Description : 
 * Generated by     : Pooya Eimandar
 * Last modified by : Pooya Eimandar on 8/5/2013
 * Comment          : 
 */

using Microsoft.Xna.Framework.Content.Pipeline;
using Microsoft.Xna.Framework.Content.Pipeline.Graphics;

namespace MSBuilder
{
    public class ImporterContext : ContentImporterContext
    {
        ContentBuildLogger logger = new MSLogger();

        public override string IntermediateDirectory 
        { 
            get 
            { 
                return string.Empty; 
            } 
        }

        public override string OutputDirectory 
        { 
            get 
            { 
                return string.Empty;
            }
        }

        public override ContentBuildLogger Logger 
        { 
            get 
            { 
                return this.logger;
            }
        }


        public override void AddDependency(string filename) 
        {

        }
    }
}
