///*
// * Copyright (c) BaziPardaz.Co Ltd. All rights reserved.
// * 
// * File Name        : UIManager.cs
// * File Description : The user interface manager
// * Generated by     : Pooya Eimandar
// * Last modified by : Pooya Eimandar on 7/27/2013
// * Comment          : 
// */
//using System.Collections.Generic;
//using Microsoft.Xna.Framework;
//using Microsoft.Xna.Framework.Graphics;
//using System;

//namespace PersianCore.Graphics.UI
//{
//    using Components;
//    using Animation;

//    public class UIManager
//    {
//       // List<MenuWindow> menuList;
//        List<UIControl> userControls;

//        public UIManager()
//        {
//          //  this.menuList = new List<MenuWindow>();
//            this.userControls = new List<UIControl>();
//        }

//        public void Load(SpriteBatch spriteBatch, SpriteFont MenuFont, Texture2D texture)
//        {
//            //var bg0 = new Texture2D(Persian.GDevice, 800, 600, false, SurfaceFormat.Color);
//            //var l = bg0.Width * bg0.Height * 4;//RGBA
//            //var a = new byte[l];

//            //for (int i = 0; i < l; i += 4)
//            //{
//            //    a[i] = 0;
//            //    a[i + 1] = 0;
//            //    a[i + 2] = 255;
//            //    a[i + 3] = 155;
//            //}

//            //bg0.SetData<byte>(a);

//            //var menuMain = new MenuWindow("Main Menu", texture/*bg0*/, MenuFont);
//           // menuMain.AddMenuItem("New Game", null);
//            menuMain.AddMenuItem("Load Game", null);
//            menuMain.AddMenuItem("Options", null);

//            menuList.Add(menuMain);
//            menuMain.Start();

//            var uc = new UIControl(new Vector2(0.7f, 0.5f), new Vector3(0, 0, 0))
//            {
//                Order = 0,
//                Color = Color.White,
//                Enable = false
//            };
//            var innerUC0 = new UIControl(new Vector2(0.07f, 0.07f), new Vector3(0.5f, 0.2f, 0))
//            {
//                Order = 0,
//                Color = Color.Red,
//                Font = MenuFont
//            };
//            var innerUC1 = new UIControl(new Vector2(0.3f, 0.3f), new Vector3(0.0f, 0.0f, 0))
//            {
//                Order = 1,
//                Color = Color.Green,
//                texture = texture,
//            };

//            innerUC0.SetText(spriteBatch, "Salam");

//            uc.AddUserControl(innerUC0);
//            uc.AddUserControl(innerUC1);

//            this.userControls.Add(uc);

//            var va = new VectorAnimation()
//            {
//                duration = TimeSpan.FromSeconds(1),
//                from = Color.Yellow.ToVector4(),
//                to = Color.Green.ToVector4(),
//            };
//            va.OnFinished += delegate(object sender, EventArgs e)
//            {
//                //(sender as UIControl).StopStoryboard();
//            };
//            innerUC0.StoryboardSetTarget(va, UIPropertyPath.EnterColor);

//            va = new VectorAnimation()
//            {
//                duration = TimeSpan.FromSeconds(1),
//                from = Color.Blue.ToVector4(),
//                to = Color.Red.ToVector4(),
//            };
//            innerUC1.StoryboardSetTarget(va, UIPropertyPath.EnterColor);

//            innerUC0.OnMouseEnter += new EventHandler(innerUC_OnMouseEnter);
//            innerUC0.OnMouseClicked += new EventHandler(innerUC_OnMouseClicked);
//        }

//        void innerUC_OnMouseClicked(object sender, EventArgs e)
//        {

//        }

//        void innerUC_OnMouseEnter(object sender, EventArgs e)
//        {

//        }

//        public void Update()
//        {
//            if (Persian.GDevice == null) return;

//            var scaleX = (float)(700.0f / Persian.GDevice.Viewport.Width);
//            var scaleY = (float)(400.0f / Persian.GDevice.Viewport.Height);
//            var world = Matrix.Identity * Matrix.CreateScale(scaleX, scaleY, 1.0f);

//            //foreach (var m in menuList)
//            //{
//            //    m.Update(world, Persian.gameTime.ElapsedGameTime.TotalMilliseconds);
//            //}

//            foreach (var uc in userControls)
//            {
//                uc.Update(false);
//            }
//        }

//        public void Draw(SpriteBatch spriteBatch)
//        {
//            //Draw UI
//            var saveState = Persian.GDevice.BlendState;
//            Persian.GDevice.BlendState = BlendState.AlphaBlend;
//            //foreach (var currentMenu in menuList)
//            //{
//            //    currentMenu.Draw(spriteBatch);
//            //}
//            foreach (var uc in userControls)
//            {
//                uc.Draw(spriteBatch);
//            }
//            Persian.GDevice.BlendState = saveState;
//        }
//    }
//}
