/*
 * Copyright (c) BaziPardaz.Co Ltd. All rights reserved.
 * 
 * File Name        : BindEventArgs.cs
 * File Description : The arguments of bind event 
 * Generated by     : Pooya Eimandar
 * Last modified by : Pooya Eimandar on 8/27/2013
 * Comment          : 
 */

using System;

namespace Core
{
    public class BindEventArgs : EventArgs
    {
        public readonly object Binding;
        public BindEventArgs(object Binding)
        {
            this.Binding = Binding;
        }
    }
}
