/*
 * Copyright (c) BaziPardaz.Co Ltd. All rights reserved.
 * 
 * File Name        : VertexMesh.cs
 * File Description : The vertex of mesh
 * Generated by     : Pooya Eimandar
 * Last modified by : Pooya Eimandar on 5/15/2013
 * Comment          : 
 */
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;

namespace PersianCore.Graphics.VertexType
{
    public struct VertexMesh : IVertexType
    {
        #region Fields

        public Vector3 Position;
        public Vector3 Normal;
        public Vector2 Texture;
        public Vector3 Tangent;
        public Vector3 Bionormal;

        #endregion

        #region Constructor

        public VertexMesh(Vector3 Position, Vector3 Normal, Vector2 Texture, Vector3 Tangent, Vector3 Bionormal)
        {
            this.Position = Position;
            this.Normal = Normal;
            this.Texture = Texture;
            this.Tangent = Tangent;
            this.Bionormal = Bionormal;
        }

        #endregion

        #region VertexDeclaration

        public static readonly VertexDeclaration _VertexDeclaration = new VertexDeclaration(
                new VertexElement(0, VertexElementFormat.Vector3, VertexElementUsage.Position, 0),
                new VertexElement(12, VertexElementFormat.Vector3, VertexElementUsage.Normal, 0),
                new VertexElement(24, VertexElementFormat.Vector2, VertexElementUsage.TextureCoordinate, 0),
                new VertexElement(32, VertexElementFormat.Vector3, VertexElementUsage.Tangent, 0),
                new VertexElement(44, VertexElementFormat.Vector3, VertexElementUsage.Binormal, 0)
            );

        public VertexDeclaration VertexDeclaration
        {
            get
            {
                return _VertexDeclaration;
            }
        }

        #endregion
    }
}
