/*
 * Copyright (c) BaziPardaz.Co Ltd. All rights reserved.
 * 
 * File Name        : TransformUC.cs
 * File Description : The Transform user control
 * Generated by     : Pooya Eimandar
 * Last modified by : Pooya Eimandar on 8/30/2013
 * Comment          : 
 */

using System.Windows.Controls;
using Telerik.Windows;

namespace PersianEditor.UserControls.RibbonComponents
{
    public partial class TransformUC : UserControl
    {
        #region Constructor

        public TransformUC()
        {
            InitializeComponent();
        }

        #endregion

        #region Events

        private void MenuItem_Click(object sender, RadRoutedEventArgs e)
        {

        }

        #endregion
    }
}
