/*
 * Copyright (c) BaziPardaz.Co Ltd. All rights reserved.
 * 
 * File Name        : XYZUC.cs
 * File Description : The xyz user control
 * Generated by     : Pooya Eimandar
 * Last modified by : Pooya Eimandar on 8/30/2013
 * Comment          : 
 */

using System.Windows.Controls;

namespace PersianEditor.UserControls.RibbonComponents
{
    public partial class XYZUC : UserControl
    {
        #region Fields & Properties

        public string UpperTextProperty
        {
            get
            {
                return this._UpperTextProperty.Text;
            }
            set
            {
                this._UpperTextProperty.Text = value;
            }
        }

        public string LowerTextProperty
        {
            get
            {
                return this._LowerTextProperty.Text;
            }
            set
            {
                this._LowerTextProperty.Text = value;
            }
        }

        #endregion

        #region Constructor

        public XYZUC()
        {
            InitializeComponent();
        }

        #endregion
    }
}
