/*
 * Copyright (c) BaziPardaz.Co Ltd. All rights reserved.
 * 
 * File Name        : TextureViewerUC.cs
 * File Description : Texture viewer user control
 * Generated by     : Pooya Eimandar
 * Last modified by : Pooya Eimandar on 9/23/2013
 * Comment          : 
 */

using System.ComponentModel;
using System.Windows.Controls;
using System.Windows.Media.Imaging;

namespace PersianEditor.UserControls
{
    public partial class TextureViewerUC : UserControl
    {
        #region Fields & Properties

        public bool IsInDesignMode
        {
            get
            {
                return DesignerProperties.GetIsInDesignMode(this);
            }
        }

        string _ImagePath;
        public string ImagePath
        {
            get
            {
                return this._ImagePath;
            }
            set
            {
                if (this._ImagePath != value)
                {
                    this._ImagePath = value;
                    try
                    {
                        BitmapImage bitmap = new BitmapImage(new System.Uri(value, System.UriKind.RelativeOrAbsolute));
                        this.ImageViewer.Source = bitmap;
                        WriteDetails(bitmap);
                    }
                    catch
                    {
                        //Bug of showing DDS
                    }
                }
            }
        }

        #endregion

        #region Constructor

        public TextureViewerUC()
        {
            if (!IsInDesignMode)
            {
                InitializeComponent();
            }
        }

        #endregion

        #region Methods

        private void WriteDetails(BitmapImage bitmap)
        {
            this.Details.Items.Clear();
            this.Details.Items.Add(string.Format("Name : {0}", System.IO.Path.GetFileName(bitmap.UriSource.AbsolutePath)));
            this.Details.Items.Add(string.Format("Format : {0}", bitmap.Format));
            this.Details.Items.Add(string.Format("Width : {0}", (int)bitmap.Width));
            this.Details.Items.Add(string.Format("Height : {0}", (int)bitmap.Height));
            this.Details.Items.Add(string.Format("Path : {0}", bitmap.UriSource.AbsolutePath));
        }

        #endregion
    }
}
